# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('chart_id', models.CharField(max_length=200)),
                ('appointment_id', models.CharField(max_length=200)),
                ('time_waiting', models.DurationField(default=datetime.timedelta(0))),
                ('seen_by_doctor', models.BooleanField(default=False)),
            ],
        ),
    ]
