# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivedpatient',
            name='ssn',
        ),
        migrations.AddField(
            model_name='arrivedpatient',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
